version: '3'
services:
  publish:
    command: npm run publish
    env_file: .env
    image: synthecypher/webassembly-example
    volumes:
      - .:/usr/src/webassembly-example
      - node_modules:/usr/src/webassembly-example/node_modules
  server:
    command: npm run watch
    env_file: .env
    image: synthecypher/webassembly-example
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/webassembly-example
      - node_modules:/usr/src/webassembly-example/node_modules
  image:
    build: .
    image: synthecypher/webassembly-example
volumes:
  node_modules: